### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by junosuarez** [codeforamerica/courtbot#1]
@pui reached out and I'm happy to help with this - @samhashemi would you be interested in pairing at some point? Let's roll up our sleeves! :umbrella:

**Comment by sb8244** [comment]
@samhashemi where is the refactor branch at? I'm looking at deploying this for Code for Atlanta and wanted some tests to get in there and have confidence in changes. Will it be merged back into master?

**Comment by samhashemi** [comment]
@sb8244 it's been a while, so I'm not sure. I think big chunks of the functionality are there, but a few pieces were missing. Looking at the tests, a few of the reminders ones are commented out, so that's probably what still needs to be added.

I'm not actively working on the project any more, so you'd have to finish it up and confirm things are working to merge it in.

**Comment by sb8244** [comment]
Thanks. I might just look into re-doing the refactor on the current master (forked to CFAtl) and learn/grow the codebase that way.

**Comment by sb8244** [comment]
Wrote some hacky tests. Minimal code change while having decent code coverage: https://github.com/codeforatlanta/courtbot/tree/master/test

Is there any chance to migrate this over to CodeForAtlanta main? It seems weird to have the fork be the new main codebase.
